version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:24.12.0
    steps:
      - checkout
      - run:
          name: Enable Corepack
          command: corepack enable
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .yarn/cache
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Test scaffolded project
          command: yarn test:scaffolded

workflows:
  ci:
    jobs:
      - build-and-test
